### ISSUE TITLE
Windows cannot find 'ALogitech Backup Settings Scripts Macros.bat'. Make sure you typed the name correctly, and then try again.

### ISSUE THREAD

**Issue by 2577manmeet** [samfisherirl/LogitechBackupandRestoreService#3]
https://media.discordapp.net/attachments/899513934388797471/937771182382534686/unknown.png

I get this error when doing anything within the program

**Comment by samfisherirl** [comment]
> https://media.discordapp.net/attachments/899513934388797471/937771182382534686/unknown.png
> 
> I get this error when doing anything within the program

did you move the app from the folder its in before installing. Download the zip, extract, do not remove from extracted folder until installed.
